Sprint 1
rizusss912/middle.messenger.praktikum.yandex pull request #1
Opened 2021-07-07 20:08 UTC by rizusss912

2021-07-08 12:32 UTC, avdoshenkov requested changes
Всё сделано круто, молодец! Свой шаблонизатор большая и ответственная штука, здорово, что решил за это взяться 👍 

Осталось поправить несколько мелочей и можно спокойно двигаться дальше.

2021-07-08 12:32 UTC, avdoshenkov commented on README.md
> +https://github.com/rizusss912/middle.messenger.praktikum.yandex/pull/1
В начале будет здорово, если добавишь название и описание проекта, чтобы было понятно, для чего вообще создан репозиторий :)

2021-07-08 12:32 UTC, avdoshenkov commented on README.md
> +    start: собирает проект и раздаёт статику через express
Здесь лучше добавить полное наименование команды, чтобы можно было просто копировать/вставить в терминал и запустить проект
```suggestion
    `npm run build`: собирает проект в папку dist
    `npm run deploy`: устанавливает зависимости и собирает проект в dist
    `npm run dev`: запускает проект локально через parcel
    `npm run start`: собирает проект и раздаёт статику через express
```

2021-07-08 12:32 UTC, avdoshenkov commented on README.md
> +WARNING:
На данном этапе такой функционал точно излишний, достаточно для каждой страницы иметь по одному файлу с шаблоном, который при сборке превращается в html-файл. Ну и по хорошему страницы должны быть со ссылками друг на друга (например, со страницы авторизации на страницу регистрации и т.д.)

2021-07-08 12:32 UTC, avdoshenkov commented on index.js
> +//const serverless = require('serverless-http');
Комментарии можно смело удалять, чтобы они не создавали визуально замусоренный вид у кода

2021-07-08 12:32 UTC, avdoshenkov commented on index.js
> +const PORT = 3000;
Здесь можно порт указать таким образом:
```suggestion
const PORT = process.env.PORT || 3000; 
```
Тогда будет возможность брать значение из env-переменных, а уже если там её не окажется, то брать значение по умолчанию

2021-07-08 12:32 UTC, avdoshenkov commented on src/utils/templator.js
> +                var parentIndex = htmlElements[htmlElements.length - 1] !== node
Лучше использовать `const` и `let`

2021-07-08 12:32 UTC, avdoshenkov commented on src/utils/templator.js
> +        for (var item of htmlConfig) {
Тут тоже лучше заменить на `let`

2021-07-08 12:32 UTC, avdoshenkov commented on src/utils/templator.js
> +//TODO: Вынести все регулярки в константы (возможно стоит переписать класс. без регулярок выйдет за o(n))
Да, регулярные выражения лучше вынести в константы с говорящим именем, чтобы было понятно, о чём выражение

2021-07-08 12:32 UTC, avdoshenkov commented on src/pages/profile/service/profile-manager.service.js
> +                phone: '8-800-555-35-35',
😏

2021-07-08 12:32 UTC, avdoshenkov commented on src/pages/profile/components/user-data/user-data.tmpl.js
> +    <ul class="field-list">
Здесь можно использовать [Description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)

2021-07-08 12:32 UTC, avdoshenkov commented on src/pages/auth/page-auth.tmpl.js
> +        <app-button click={{onAuthorization()}} appearance="primary">
По хорошему кнопка должна быть частью формы, чтобы по её нажатию автоматически срабатывал `submit`

2021-07-08 12:32 UTC, avdoshenkov commented on src/components/input/app-input.tmpl.js
> +    <slot name="title"></slot>
Для каждого инпута хорошо иметь свой [лейбл](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label), а связать их между собой можно с помощью атрибута `id` у инпута и [`for`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for) у лейбла. Соответственно, его тоже хорошо бы передавать в качестве пропса

2021-07-08 12:32 UTC, avdoshenkov commented on src/components/button/app-button.less
> +        outline: none;
Поскольку отключено поведение браузера по умолчанию, очень хорошо будет, если самостоятельно реализуешь замену. Как минимум для ховера и фокуса смена цвета фона. Ещё как вариант добавить `cursor: pointer`, чтобы возникало понимание, что элемент интерактивный

2021-07-08 20:50 UTC, rizusss912 commented on src/pages/auth/page-auth.tmpl.js
> +        <app-button click={{onAuthorization()}} appearance="primary">
у меня вроде как уже есть хук на этой кнопке, которому доступна форма и Если я буду добавлять её в саму форму, то придётся превентить дефолтный submit чтобы он не вызывал сайдэфекты. Вообще я тут хочу повторить архитектуру ангуляра и пробрасывать объект формы из верхнего элемента в app-form и возможно у него будет хук onSubmit

2021-07-09 05:54 UTC, avdoshenkov commented on src/pages/auth/page-auth.tmpl.js
> +        <app-button click={{onAuthorization()}} appearance="primary">
Это да, обработка клика есть, но по логике строения формы её данные как-то должны отправляться из неё самой. Например, на странице может быть отключён JS у пользователя в браузере, и тогда такая схема, когда кнопка вне формы, не сработает. К тому же достаточно распространённый паттерн, когда заполняешь поля формы и жмёшь в конце на Enter, чтобы произошла отправка формы. В текущей реализации для этого нужно будет накручивать лишнюю логику.

А в плане того, чтобы превентить дефолтный сабмит — это нормально, главное понимать, что и зачем делаешь :)

2021-07-09 05:58 UTC, avdoshenkov approved these changes
Отлично поработал, молодец!

2021-07-09 05:58 UTC, avdoshenkov commented on src/utils/templator.js
> +    // node.querySelector("slot[name="name"]")
Комментарий можно смело удалять

2021-07-10 13:01 UTC, merged